"""initial migration

Revision ID: 48676342515a
Revises: None
Create Date: 2014-08-05 17:13:10.323228

"""

# revision identifiers, used by Alembic.
revision = '48676342515a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashmap_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('hashmap_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['hashmap_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'name', name='uniq_map_service_field'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('hashmap_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('map_type', sa.Enum('flat', 'rate', name='enum_map_type'), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['hashmap_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'field_id', name='uniq_mapping'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashmap_alembic',
    sa.Column('version_num', sa.VARCHAR(length=32), nullable=False)
    )
    op.drop_table('hashmap_maps')
    op.drop_table('hashmap_fields')
    op.drop_table('hashmap_services')
    ### end Alembic commands ###
