"""initial migration

Revision ID: 464e951dc3b8
Revises: None
Create Date: 2014-08-05 17:41:34.470183

"""

# revision identifiers, used by Alembic.
revision = '464e951dc3b8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.BigInteger(), nullable=False),
    sa.Column('s_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('modules_state',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloudkitty_alembic',
    sa.Column('version_num', sa.VARCHAR(length=32), nullable=False)
    )
    op.drop_table('modules_state')
    op.drop_table('states')
    ### end Alembic commands ###
